= Spring Boot Kotlin Native example (with Gradle)

Simple showcase of Spring Boot Native compilation for Kotlin projects.

== Issues

== Private methods in RestController(s) are not detected

The class had to be explicitly added as a Hint (See class `AppNativeHints`).

```kotlin
hints.reflection()
        .registerType(HelloController::class.java, MemberCategory.INVOKE_DECLARED_METHODS)
```

Private methods in `@Component` services are fine.


NOTE: Private methods in Kotlin are `KCallable`, not normal Java `Method`.
Trying to list it to only register it did not work.

=== compileOnly dependencies are not considered for processAot

`ReflectionsRuntimeHintsRegistrar` uses https://github.com/ronmamo/reflections[Reflections project] to register all classes under certain packages for reflection.
Given this is only required to generate the AOT configuration I would expect that dependencies required by Hints could be set as `compileOnly`.

This is specially an issue when releasing both JVM and Native versions, since the JVM will include the dependencies in the package (for instance when releasing a Docker/OCI image).

**TLDR;** running `./gradlew processAot` fails with, changing the dependency to `implementation` fixes it.

```
Exception in thread "main" org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.demokotlinnative.aot.ReflectionsRuntimeHintsRegistrar]: Unresolvable class definition
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:150)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
        at org.springframework.context.aot.RuntimeHintsBeanFactoryInitializationAotProcessor.lambda$processAheadOfTime$1(RuntimeHintsBeanFactoryInitializationAotProcessor.java:63)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.context.aot.RuntimeHintsBeanFactoryInitializationAotProcessor.processAheadOfTime(RuntimeHintsBeanFactoryInitializationAotProcessor.java:62)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.getContributions(BeanFactoryInitializationAotContributions.java:67)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:49)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:44)
        at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
        at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
        at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
        at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:76)
Caused by: java.lang.NoClassDefFoundError: org/reflections/Configuration
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3429)
        at java.base/java.lang.Class.getConstructor0(Class.java:3634)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2810)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:141)
        ... 15 more
Caused by: java.lang.ClassNotFoundException: org.reflections.Configuration
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 20 more
```
